### ISSUE TITLE
Atividades Bootcamp GFT Quality Assurance #1

### ISSUE THREAD

**Issue by maxwelldantas** [maxwelldantas/dio#3]
Cursos, desafios de projeto, desafios de códigos e lives realizadas no Bootcamp GFT Quality Assurance #1.

Cursos:
- [x] GFT Quality Assurance #1
- [x] Lógica de Programação Essencial
- [x] Aprenda o que são Estrutura de Dados e Algoritmos
- [x] Projetos ágeis com SCRUM
- [x] Introdução ao Git e ao GitHub
- [x] Dominando IDEs Java
- [x] Variáveis, Tipos de Dados e Operadores Matemáticos em Java
- [ ] Entendendo Métodos Java
- [ ] Lógica Condicional e Controle de Fluxos em Java
- [ ] Estruturas de Repetição e Arrays em Java
- [ ] Reforçando o Conceito de Laços em Java
- [ ] Introdução a orientação a objetos com Java
- [ ] Debugging Java
- [ ] Tratamento de Exceções em Java
- [ ] Trabalhando com Collections Java
- [ ] Introdução a APIs e métodos HTTP
- [ ] Introdução ao Mercado de Qualidade de Software
- [ ] Introdução a Testes de Software
- [ ] Testes Unitários Com JUnit
- [ ] Aprenda a aplicar testes com Java

Mentoria (Live):
- [ ] Mentoria #1: Aula Inaugural - Bootcamp GFT Quality Assurance #1

Desafio de código:
- [ ] Desafios - GFT QA #1
- [ ] Mais Desafios - GFT QA #1
- [ ] Desafios Intermediários - GFT QA #1

Desafio de projeto:
- [ ] Criando um Banco Digital com Java e Orientação a Objetos
- [ ] Abstraindo um Bootcamp Usando Orientação a Objetos em Java
